module.exports = {
// ACTIONS:
  apiActions: 'client/actions/apiActions',
  formActions: 'client/actions/formActions',
  playlistActions: 'client/actions/playlistActions',
  songActions: 'client/actions/songActions',
// CONSTANTS:
  constants: 'client/constants',
  actionTypes: 'client/actions/types',
// FRONT END ROUTES:
  Routes: 'client/Routes',
// COMPONENTS:
  App: 'client/App',
	Navbar: 'client/components/Navbar',
	Home: 'client/components/Home',
  HiddenGems: 'client/components/HiddenGems',
  TasteTests: 'client/components/TasteTests',
  SeeingSounds: 'client/components/SeeingSounds',
  NewMusic: 'client/components/NewMusic',
  GuardianArticle: 'client/components/GuardianArticle',
  NPRArticle: 'client/components/NPRArticle',
  CreatePlaylist: 'client/components/CreatePlaylist',
  CreateSong: 'client/components/CreateSong',
  CreateArtist: 'client/components/CreateArtist',
  CreateGenre: 'client/components/CreateGenre',
  CreateProducer: 'client/components/CreateProducer',
  CreateAlbum: 'client/components/CreateAlbum',
  DisplayPlaylists: 'client/components/DisplayPlaylists',
  SinglePlaylist: 'client/components/SinglePlaylist',
  SingleSong: 'client/components/SingleSong',
  DisplayAllSongs: 'client/components/DisplayAllSongs',
  SinglePlaylistSongs: 'client/components/SinglePlaylistSongs',
// CONTAINERS: 
  HomeContainer: 'client/containers/HomeContainer',
  CreatePlaylistContainer: 'client/containers/CreatePlaylistContainer',
  CreateSongContainer: 'client/containers/CreateSongContainer',
  CreateArtistContainer: 'client/containers/CreateArtistContainer',
  CreateGenreContainer: 'client/containers/CreateGenreContainer',
  CreateProducerContainer: 'client/containers/CreateProducerContainer',
  CreateAlbumContainer: 'client/containers/CreateAlbumContainer',
  DisplayPlaylistsContainer: 'client/containers/DisplayPlaylistsContainer',
  DisplayAllSongsContainer: 'client/containers/DisplayAllSongsContainer',
  SinglePlaylistSongsContainer: 'client/containers/SinglePlaylistSongsContainer',
// STORE:
  store: 'client/store',
// REDUCERS:
  rootReducer: 'client/reducers/rootReducers',
  apiReducer: 'client/reducers/apiReducer',
  formReducer: 'client/reducers/formReducer',
  playlistReducer: 'client/reducers/playlistReducer',
  songReducer: 'client/reducers/songReducer'
}