export const GET_GUARDIAN_DATA = "GET_GUARDIAN_DATA";

export const GET_NPR_DATA = "GET_NPR_DATA";

export const CREATE_PLAYLIST = "CREATE_PLAYLIST";

export const CREATE_SONG = "CREATE_SONG";

export const CREATE_ARTIST = "CREATE_ARTIST";

export const CREATE_GENRE = "CREATE_GENRE";

export const CREATE_PRODUCER = "CREATE_PRODUCER";

export const CREATE_ALBUM = "CREATE_ALBUM";

export const DISPLAY_PLAYLISTS = "DISPLAY_PLAYLISTS";

export const DISPLAY_ALL_SONGS = "DISPLAY_ALL_SONGS";

export const UPDATE_CURRENT_PLAYLIST = "UPDATE_CURRENT_PLAYLIST";